name       : perl-try-tiny
version    : '0.28'
release    : 3
source     :
    - http://search.cpan.org/CPAN/authors/id/E/ET/ETHER/Try-Tiny-0.28.tar.gz : f1d166be8aa19942c4504c9111dade7aacb981bc5b3a2a5c5f6019646db8c146
license    : MIT
component  : programming.perl
summary    : minimal try/catch with proper preservation of $@
description: |
    minimal try/catch with proper preservation of $@
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
