name       : perl-try-tiny
version    : 0.27
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/E/ET/ETHER/Try-Tiny-0.27.tar.gz : 8abf0878c9cddc0c4ab9c4adfa8d81790a16d7cb53b0e429430b13b7567075fb
license    : MIT
component  : programming.perl
summary    : minimal try/catch with proper preservation of $@
description: |
    minimal try/catch with proper preservation of $@
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
