name       : perl-try-tiny
version    : '0.31'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/E/ET/ETHER/Try-Tiny-0.31.tar.gz : 3300d31d8a4075b26d8f46ce864a1d913e0e8467ceeba6655d5d2b2e206c11be
homepage   : https://metacpan.org/pod/Try::Tiny
license    : MIT
component  : programming.perl
summary    : Try::Tiny - Minimal try/catch with proper preservation of $@
description: |
    This module provides bare bones try/catch/finally statements that are designed to minimize common mistakes with eval blocks, and NOTHING else.
builddeps  :
    - perl-capture-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
