name       : perl-try-tiny
version    : '0.30'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/E/ET/ETHER/Try-Tiny-0.30.tar.gz : da5bd0d5c903519bbf10bb9ba0cb7bcac0563882bcfe4503aee3fb143eddef6b
license    : MIT
component  : programming.perl
summary    : minimal try/catch with proper preservation of $@
description: |
    minimal try/catch with proper preservation of $@
builddeps  :
    - perl-capture-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
